export default {

    FONT_SIZE_SMALL: 14,
    FONT_SIZE_MEDIUM: 16,
    FONT_SIZE_LARGE: 20,
    PRIMARY_COLOR: 'rgb(30, 147, 242)',
    SECONDARY_COLOR: 'rgb(238, 167, 2)',
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    BACKGROUND_COLOR_DEFAULT: 'red',
    BACKGROUND_COLOR_MODAL: '#eee',
  };